DELETE http://localhost:8080/events/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBrcjEyQHBrci5jb20iLCJleHAiOjE3MjcwMTUwMDAsInVzZXJJRCI6MX0.N9HMx4lwltARpkBr9X-q-_8yoPBL0B4sPJec8V2m5iY

