POST http://localhost:8080/events
content-type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBrcjEyQHBrci5jb20iLCJleHAiOjE3MjcwMTUwMDAsInVzZXJJRCI6MX0.N9HMx4lwltARpkBr9X-q-_8yoPBL0B4sPJec8V2m5iY

{
  "name": "PKR event need to delete",
  "description": "A test event",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}