postgres:
	docker run --name postgres12 --network bank-network -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -d postgres:12-alpine

createdb:
	docker exec -it postgres12 createdb --username=root --owner=root simple_bank

dropdb:
	docker exec -it postgres12 dropdb simple_bank

migrateup:
	migrate -path  db/migration/ --database "postgresql://root:secret@localhost:5432/simple_bank?sslmode=disable" --verbose up

migrateup1:
	migrate -path  db/migration/ --database "postgresql://root:secret@localhost:5432/simple_bank?sslmode=disable" --verbose up 1

awsmigrate1:
	migrate -path  db/migration/ --database "postgresql://root:2mfPOhsMmu54gCowbY1T@simple-bank.cl82ao6aizwx.ap-south-1.rds.amazonaws.com:5432/simple_bank" --verbose up 1

migratedown:
	migrate -path  db/migration/ --database "postgresql://root:secret@localhost:5432/simple_bank?sslmode=disable" --verbose down

migratedown1:
	migrate -path  db/migration/ --database "postgresql://root:secret@localhost:5432/simple_bank?sslmode=disable" --verbose down 1

sqlc:
	sqlc generate

test :
	go test -v -cover ./...

server:
	go run main.go

bank:
	docker run  --name simplebank --network bank-network -p 8080:8080 -e DB_SOURCE="postgresql://root:secret@postgres12:5432/simple_bank?sslmode=disable" simplebank:latest

mock:
	mockgen -package mockdb -destination db/mock/store.go github.com/rpraveenkumar/Golang/db/sqlc Store

.PHONY: postgres createdb dropdb migrateup migrateup1 migratedown migratedown1 sqlc server bank mock awsmigrate1
